### ISSUE TITLE
Can't add currencies in latest EconomyLite

### ISSUE THREAD

**Issue by tridaak** [Flibio/EconomyLite#46]
Was trying to create a currency (pkd), but whenever I start the server up after changing the config, it adds a coin currency which it uses instead.
I can change the plural, singular, and symbol of coin to the currency I need however.

**Comment by Flibio** [comment]
Are you adding currency via the commands or directly modifying the configuration file?

**Comment by tridaak** [comment]
Modifying the configuration file.

**Comment by Flibio** [comment]
I would try to add the currency via the commands, a small mistake in the configuration file can botch the whole thing.

**Comment by tridaak** [comment]
pkd {
    plural=PokeDollars
    singular=PokeDollar
    symbol=P
}
current=pkd

This was my config. I just edited the coin currency to have the same values, so that's working fine.

**Comment by Flibio** [comment]
The way EconomyLite stores data does not allow you to directly change the id of the currency, which in your case is `pkd`. However you can change the plural, singular, and symbol values. If you change the is back to coin, it should work. With that being said, I still recommend adding a new currency instead of modifying the default one.

**Comment by tridaak** [comment]
Oh, didn't know that. Thanks for the insight.
